version: "3"

services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ProftaakS61MW!
      POSTGRES_DB: postgres/postgresdb
    ports:
      - 5432:5432
  testapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
      - mongodb
      - kafka
    ports:
      - 8080:8080

#  rabbitmq:
#    container_name: "amqp-test"
#    image: rabbitmq:3-management
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: password
#    ports:
#      - 8081:15672
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
